services:
  container:
    image: kokeh/hu_bioinfo:stable
    environment:
      - DISABLE_AUTH=true
      - GITHUB_PAT={{GITHUB_PAT}}
      - PREM_DIR="/home/user/prem"
      - PROJ_DIR="/home/user/proj"
    volumes:
      - {{CACHE_FOLDER}}:/home/user/prem
      - {{PROJECT_FOLDER}}:/home/user/proj
    command: sleep infinity