#!/usr/bin/env bash
set +e
#set -euo pipefail
set -x

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

PWD=$(pwd)

# ライブラリ読み込み
source "$SCRIPT_DIR/lib.sh"

# ヘルプメッセージ
usage() {
    echo "Usage: prem <command> <target> [options]"
    echo "Commands:"
    echo "  mkenv      make new environment."
    echo "  rmenv      Execute 'hoge' on target"
    echo "  mkproj     Execute 'hoge' on target"
    echo "  setenv     Execute 'hoge' on target"
    echo "  rmproj     Execute 'hoge' on target"
    echo "Options:"
    echo "  -o=yes    Example option"
}

# 引数チェック
if [ $# -lt 2 ]; then
    log_error "Invalid arguments."
    usage
else
    COMMAND=$1
    shift 1  # 最初の1つの引数を削除し、残りをオプションとして扱う

    # コマンド実行
    case "$COMMAND" in
        init)
            init "$@"
            ;;
        # 環境作成
        mkenv)
            mkenv "$@"
            ;;

        # 環境削除
        rmenv) 
            rmenv "$@"
            ;;
        
        rm_all)
            rm_all "$@"
            ;;

        # プロジェクト作成
        mkproj)
            if [ "$#" -lt 3 ]; then
                echo "Usage: mkproj proj-name -p python-env-name -r r-env-name"
            else
                mkproj "$TARGET" "$@"
            fi
            ;;

        # プロジェクトの環境変更
        setenv)
            setenv "$@"
            ;;

        # プロジェクト削除
        rmproj)
            if [ "$#" -ne 1 ]; then
                echo "Usage: rmproj proj-name"
            else
                rmproj "$TARGET"
            fi
            ;;

        *)
            log_error "Unknown command: $COMMAND"
            usage
            ;;
    esac
fi