#!/bin/bash

# GitHubトークンが設定されていない場合は入力を促す
if [ -z "$GITHUB_PAT" ]; then
  read -sp "input GitHub personal access token: " GITHUB_PAT
  echo
fi

# gh CLIでのログイン
echo "$GITHUB_PAT" | gh auth login --with-token