#!/bin/sh

dir_path="/home/user/wd/proj/$1"

if [ -d $dir_path ]; then
    echo "$dir_path exists. Try in another name."
fi
if [ ! -d $dir_path ]; then
    cd /home/user/wd/proj
    uv init $1
    cd $dir_path
    # uv venv
    Rscript -e 'library(renv)' -e 'renv::init()' -e 'q()' --no-save
    
    rm .git -r
    rm .gitignore
    rm hello.py
    rm README.md
    rm .python-version
fi