#!/bin/sh

dir_path="/home/user/wd/proj/$1"

if [ -d $dir_path ]; then
    echo "$dir_path exists. Try in another name."
fi
if [ ! -d $dir_path ]; then
    uv init $dir_path
    cd $dir_path
    uv venv
    R --no-save
    Rscript -e 'print("done")' --no-save
    
    rm .git -r
    rm .gitignore
    rm hello.py
    rm README.md
    rm .python-version
fi