#!/bin/bash

dir_path="/home/user/wd/proj/$1"

if [ -d $dir_path ]; then
    cd $dir_path

    uv add ipykernel
    uv run ipython kernel install --user --name=$1-py

    Rscript -e "
    renv::install('IRkernel')
    library(IRkernel)
    IRkernel::installspec(name = '$1-r')
    "
fi
if [ ! -d $dir_path ]; then
    echo "$dir_path doesn't exist. Check the proj name."
fi