#!/bin/bash

cd /home/user/wd/proj/$1

uv add ipykernel
uv run ipython kernel install --user --name=$1-py

Rscript -e "
renv::install('IRkernel')
library(IRkernel)
IRkernel::installspec(name = '$1-r')
"
