services:
  container:
    image: kokeh/hu_bioinfo:stable
    environment:
      - DISABLE_AUTH=true
      - GITHUB_PAT=${GITHUB_PAT}
      - CACHE_DIR="/home/user/cache"
      - PROJ_DIR="/home/user/proj"
    volumes:
      - ../projects:/home/user/cache
      - ../../cache:/home/user/proj
    env_file:
      - .env
    command: sleep infinity
