services:
  container:
    image: kokeh/hu_bioinfo:stable
    environment:
      - DISABLE_AUTH=true
      - GITHUB_PAT=${GITHUB_PAT}
      - PREM_DIR="/home/user/prem"
      - PROJ_DIR="/home/user/proj"
    volumes:
      - $PREM_DIR:/home/user/prem
      - $PROJ_DIR:/home/user/proj
    env_file:
      - .env
    command: sleep infinity
