services:
  container:
    image: kokeh/hu_bioinfo:stable
    environment:
      - DISABLE_AUTH=true
    volumes:
      - ../projects:/home/user/proj
      - ../../cache:/home/user/cache
    env_file:
      - .env
    command: sleep infinity
