services:
  container:
    image: kokeh/hu_bioinfo:slim
    environment:
      - DISABLE_AUTH=true
      - GITHUB_PAT=${GITHUB_PAT}
    volumes:
      - ../../wd:/home/user/wd
    env_file:
      - .env
    command: sleep infinity
