apt-get update
apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    libssl-dev \
    libcurl4-openssl-dev \
    libreadline-dev \
    wget \
    libpcre2-8-0 \
    locales \
    tzdata \
    cmake \
    libzmq3-dev \
    libopenblas-dev \
    liblapack-dev \
    libatlas-base-dev \
    g++ \
    gfortran \
    libsqlite3-dev \
    libxml2-dev \
    libxslt1-dev \
    libhdf5-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    git \
    gh \
    nvi \
    zlib1g-dev \
    libbz2-dev \
    tk \
    tk-dev \
    tk-table \
    libffi-dev \
    libfreetype6-dev \
    libfontconfig1-dev \
    libgmp3-dev \
    libmpfr-dev \
    libgsl0-dev \
    libcairo2-dev \
    libfftw3-dev \
    libx11-dev \
    libxt-dev \
    make \
    libmariadb-dev-compat \
    libmariadb-dev \
    unixodbc-dev \
    libnode-dev \
    default-jdk \
    libxml2-dev \
    libssh2-1-dev \
    libglpk-dev \
    imagemagick \
    libmagick++-dev \
    gsfonts \
    python3 \
    libglu1-mesa-dev \
    libgl1-mesa-dev \
    libgdal-dev \
    gdal-bin \
    libgeos-dev \
    libproj-dev \
    libsodium-dev \
    libicu-dev \
    tcl \
    libfribidi-dev \
    libharfbuzz-dev \
    libudunits2-dev
