apt-get update
apt-get install -y --no-install-recommends \
    build-essential \
    bash-completion \
    ca-certificates \
    libssl-dev \
    curl \
    libcurl4-openssl-dev  \
    libreadline-dev \
    wget \
    libpcre2-8-0 \
    locales \
    tzdata \
    llvm \
    "libicu[0-9][0-9]" \
    cmake \
    gdb \
    valgrind \
    libzmq3-dev \
    ncurses-dev \
    xclip \
    libopenblas-dev \
    liblapack-dev \
    libatlas-base-dev \
    g++ \
    gfortran \
    libsqlite3-dev \
    libxml2-dev \
    libxslt1-dev \
    libhdf5-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    htop \
    parallel \
    git \
    zlib1g-dev \
    libbz2-dev \
    zip \
    unzip \
    tk-dev \
    libffi-dev \
    libfreetype6-dev \
    libfontconfig1-dev \
    libgmp3-dev \
    libmpfr-dev \
    jags \
    libgsl0-dev \
    libcairo2-dev \
    libfftw3-dev \
    libx11-dev \
    libxt-dev \
    nvi \
    apt-utils